{
	"version": 1682865728,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/tiledbackground.png",
		"images/ground-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/bullet-sheet0.png",
		"images/rock-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/hpbar-sheet0.png",
		"images/hp-sheet0.png",
		"images/retry-sheet0.png",
		"images/tiledbackground2.png",
		"images/finishline-sheet0.png",
		"images/tiledbackground3.png",
		"images/restart-sheet0.png",
		"images/tiledbackground4.png",
		"media/8 bit death sound effect.m4a",
		"media/8 bit death sound effect.ogg",
		"media/8 bit victory sound effect.m4a",
		"media/8 bit victory sound effect.ogg",
		"media/8-bit hit sound effect.m4a",
		"media/8-bit hit sound effect.ogg",
		"media/frog sound effect _ribbit_.m4a",
		"media/frog sound effect _ribbit_.ogg",
		"media/the powerpuff girls end credits (8-bit reimagining).m4a",
		"media/the powerpuff girls end credits (8-bit reimagining).ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/theme.m4a",
		"media/theme.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}